name: tapkat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  algolia: ^1.0.1
  auto_size_text: ^3.0.0
  built_collection: ^5.1.1
  built_value: ^8.0.4
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.13
  equatable: ^2.0.3
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.9
  google_maps_flutter_web: ^0.3.2+1
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.4.0+1
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  json_path: ^0.3.0
  json_serializable: ^6.1.5
  mime_type: ^1.0.0
  page_transition: ^2.0.4
  rxdart: ^0.27.3
  sign_in_with_apple: ^3.3.0
  timeago: ^3.1.0
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.4
  change_app_package_name: ^1.0.0
  flutter_svg: ^1.0.0
  carousel_slider: ^4.0.0
  modal_bottom_sheet: ^2.0.0
  flutter_progress_hud: ^2.0.0
  dio: ^4.0.4
  curl_logger_dio_interceptor: ^0.0.2
  http_parser: ^4.0.0
  http: ^0.13.4
  photo_view: ^0.14.0
  flutter_image_compress: ^1.1.0
  permission_handler: ^8.3.0
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  sliding_up_panel: ^2.0.0+1
  geolocator: ^8.1.1
  geocoding: ^2.0.2
  infinite_scroll_pagination: ^3.1.0
  localstorage: ^4.0.0+1
  image: ^3.1.3
  path_provider: ^2.0.9
  # firebase_messaging: ^11.2.7
  flutter_rating_bar: ^4.0.0
  toggle_switch: ^1.4.0
  pull_to_refresh: ^2.0.0
  crypto: ^3.0.1
  device_info_plus: ^3.2.2
  firebase_messaging: ^11.2.11
  notification_permissions: ^0.6.1
  flutter_local_notifications: ^9.4.0
  device_preview: ^1.0.0
  connectivity_plus: ^2.3.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.20
  distance: ^1.0.0
  flutter_phoenix: ^1.0.0
  intl_phone_number_input: ^0.7.0+2
  firebase_dynamic_links: ^4.2.2
  share_plus: ^4.0.4
  label_marker: ^1.0.1
  flutter_logs: ^2.1.5
  flutter_email_sender: ^5.1.0
  currency_text_input_formatter: ^2.1.5
  loading_indicator: ^3.0.0
  sticky_headers: ^0.2.0
  gallery_saver: ^2.3.2
  sticky_infinite_list: ^4.0.1
  scroll_to_index: ^2.1.1

dev_dependencies:
  build_runner: ^2.1.2
  built_value_generator: ^8.0.4
  flutter_launcher_icons: ^0.9.2  
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/app_icon.png'

flutter_native_splash:
  image: assets/icons/splash_icon.png
  color: 'FFFFFF'
  android_disable_fullscreen: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300