// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPjfTTLzdfp-56tarHguvLXgdw7QAGkg',
    appId: '1:317757606033:web:4e0e72f4ea42df7af99730',
    messagingSenderId: '317757606033',
    projectId: 'map-surf',
    authDomain: 'map-surf.firebaseapp.com',
    storageBucket: 'map-surf.appspot.com',
    measurementId: 'G-4HB1P3JPH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH4fWM5IbEO0X-Txkm6HNsFAQ3KOfW20I',
    appId: '1:317757606033:android:0b206fb583c944abf99730',
    messagingSenderId: '317757606033',
    projectId: 'map-surf',
    storageBucket: 'map-surf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyNgeJDA8_nwdGrPf5ecuIsVFRXSF0mQ',
    appId: '1:317757606033:ios:2c55667e58e345a8f99730',
    messagingSenderId: '317757606033',
    projectId: 'map-surf',
    storageBucket: 'map-surf.appspot.com',
    androidClientId: '317757606033-1u5unb3ore1vhu8veibr9933qb8abffi.apps.googleusercontent.com',
    iosClientId: '317757606033-4f63utln10gcr8nhn9crig9ot6mhaltl.apps.googleusercontent.com',
    iosBundleId: 'com.flutterflow.tapkat',
  );
}
